#!/bin/bash
echo "Setting up Agent MedIC environment..."
echo "Step 1: Install SigNoz via Foundry"
echo "  signoz install"
echo ""
echo "Step 2: Start services"
echo "  docker compose up -d"
echo ""
echo "Step 3: Pull Ollama model"
echo "  docker exec -it $(docker compose ps -q ollama) ollama pull llama3.2"
echo ""
echo "Step 4: Initialize database"
echo "  docker compose exec agent-medic python -c \"from db.models import Base, engine; Base.metadata.create_all(bind=engine)\""
echo ""
echo "Done! Open http://localhost:3000"
